### ISSUE TITLE
Combobox - Select component refactoring

### ISSUE THREAD

**Issue by Andrevmatias** [laboratoriobridge/bold#620]
Due to the large number of issues for the `Select` component, we are refactoring it to the new `Combobox` component.
This new Combobox component is built using the new [`useCombobox` downshift hook](https://www.downshift-js.com/use-combobox) instead of the `<Downshift />` component `Select` currently uses.

The idea is to use **extensive jest tests** to cover all scenarios and currently open bugs.

The new component should be compatible with all the Select component properties and [specifications](https://www.figma.com/file/TE9FUDtlgVQ4FWlAPtTagxQU/Bold-Design-System?node-id=3750%3A44) and this refactoring should address:

- [x] #466
- [x] #519 
- [x] #520 
- [x] #532 
- [x] #581 
- [x] #586 
- [x] #607 
- [x] #608 
- [x] #761 
- [x] #811

***

# Migration

The `Select` component will be kept in the codebase allowing users to gradually change from `Select` to `Combobox` component.

***

# Tasks

- [x] #621 - Implement a simple, ARIA compliant, single-select component using the `useCombobox` hook
- [x] #627 - Implement a single-select  component accordingly to the [specifications](https://www.figma.com/file/TE9FUDtlgVQ4FWlAPtTagxQU/Bold-Design-System?node-id=3750%3A44)
- [x] #648 - Add support to custom components
- [x] #652 - Implement "suggestion" component
- [x] #661 - Add support to async load items
- [x] #687
- [x] #764
- [x] #804
- [x] #812
- [x] #823
- [x] #822

**Comment by Gregory-Scandolara** [comment]
issue com os bugs encontrados #25598
