### ISSUE TITLE
[Chart]  Allow the use of stroke line without dashes

### ISSUE THREAD

**Issue by zDudaHang** [laboratoriobridge/bold#851]
## Component to amend
Chart - Reference Area

## Visual
As you can see in P34 and P18, the stroke line is without dashes

![Screenshot from 2024-09-03 10-51-06](https://github.com/user-attachments/assets/5a484f3b-7c25-4575-954a-26629c9858f7)

You need to change [this line](https://github.com/laboratoriobridge/bold/blob/main/src/components/Chart/renderSeries.tsx#L54)

**Comment by zDudaHang** [comment]
```[tasklist]
### Tasks (@AndresKindel)
- [ ] Request @Andrevmatias's review
- [ ] Add knobs to the new(s) prop(s) [here](https://bold.bridge.ufsc.br/storybook/?path=/story/components-chart--reference-area)
- [ ] Everything must be in English
- [ ] Check if it's necessary to add something to i18n
- [ ] Update snapshot testes
- [ ] Add new tests to the component
```

**Comment by wesleydecezere** [comment]
Site spec will be update in another issue.
